# Generated by Django 3.0 on 2022-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220407_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_closed',
            field=models.DateField(null=True),
        ),
    ]
