# Generated by Django 3.0 on 2022-04-10 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220407_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_closed',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
    ]
