# Generated by Django 3.0 on 2022-04-10 14:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20220410_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Done', 'Done'), ('Freezes', 'Freezes')], default='New', max_length=15)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='High', max_length=15)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.date(2022, 4, 17))),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('users_id', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
