# Generated by Django 3.0 on 2022-05-10 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220509_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_action', to='api.Project'),
        ),
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_action', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_closed',
            field=models.DateField(default=datetime.date(2022, 5, 17)),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 5, 17)),
        ),
    ]
